#define PORTAL_SONG E__NOTE(_G5), E__NOTE(_REST), E__NOTE(_FS5), E__NOTE(_REST), E__NOTE(_E5), E__NOTE(_REST), E__NOTE(_E5), E__NOTE(_REST), H__NOTE(_FS5)

#define TEMPO_DEFAULT 60
#define TIMBRE_DEFAULT TIMBRE_12
#undef STARTUP_SONG
#define STARTUP_SONG SONG(PORTAL_SONG)

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
